name: nuget package release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        pushd ./src/ResultBoxes
        dotnet restore ResultBoxes.sln
    - name: Build with dotnet
      run: |
        pushd ./src/ResultBoxes
        dotnet build ResultBoxes.sln -c Release
    - name: Pack ResultBoxes
      run: |
        dotnet nuget push "src/ResultBoxes/ResultBoxes/bin/Release/ResultBoxes.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
  